# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenizer < Formula
  desc "A fast CLI tool to count tokens for various Large Language Model (LLM) providers."
  homepage "https://github.com/zahidcakici/tokenizer-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zahidcakici/tokenizer-cli/releases/download/v0.1.3/tokenizer-cli_0.1.3_darwin_amd64.tar.gz"
      sha256 "73cb9cee437cdbc184cac0d346bc5895372511cc5d334ebfcfc5e475ad5fdc7e"

      def install
        bin.install "tokenizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zahidcakici/tokenizer-cli/releases/download/v0.1.3/tokenizer-cli_0.1.3_darwin_arm64.tar.gz"
      sha256 "7f4bc1bfd5a876b49fbbaa33e9a0731294a432886dc0b4e6e949e09be6e7fc3d"

      def install
        bin.install "tokenizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zahidcakici/tokenizer-cli/releases/download/v0.1.3/tokenizer-cli_0.1.3_linux_amd64.tar.gz"
      sha256 "43e8bcd41c02928c6cdaf3694e4c94a8e016b0d35bc0a2f77b349c900371a924"
      def install
        bin.install "tokenizer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zahidcakici/tokenizer-cli/releases/download/v0.1.3/tokenizer-cli_0.1.3_linux_arm64.tar.gz"
      sha256 "c730602b0a204a90cb17492f0f8a8490738fc3a5283331a7ac4c36a5979979e8"
      def install
        bin.install "tokenizer"
      end
    end
  end

  test do
    system "#{bin}/tokenizer", "--help"
  end
end
